version: '3'

services:
  crawler:
    build: ./crawler
    volumes:
     - ./data:/data
    command: "crawl --timeout 10m --table /data/crawler.db"
  
  api:
    build: ./api
    network_mode: "host" 
    volumes:
     - ./data:/data
    depends_on:
     - crawler
    command: "--crawler-db-path /data/crawler.db --api-db-path /data/api.db"

  frontend:
    build: ./web
    network_mode: "host"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - api

